site_name: Software Development Notes
nav:
  - Home: index.md
  - Software Development Essentials:
    - Getting Started: swe/gettingstarted.md
    - HTTP Basics: swe/httpbasics.md
    - FastAPI:
        - Tutorial: swe/fastapitutorial.md
        - Validation: swe/fastapivalidation.md
    - Backend:
        - Service Layer and Dependency Injection: swe/servicelayerdi.md
        - Introduction to Testing: swe/testing.md
        - Introduction to CI/CD: swe/cicd.md
  - GigMatcher:
    - DataLoading: gigmatcher/dataloading.md
theme:
  icon:
    logo: fontawesome/solid/computer
  name: material
  palette:
    scheme: slate
    primary: light blue
    accent: light blue
  features:
    - navigation.path

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true